<?php

 $title = 'Cadastrar Dieta';
 $this->headTitle($title);

 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php $form->prepare(); ?>
<?php echo $this->form($this->form); ?>
 <?php
 
// echo var_dump($this->form());
/* $form->setAttribute('action', $this->url('cadastrarAluno', array('action' => 'add')));
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->formCollection($form);
  
  
 */
 
 
?>

<!--
<div class="form-group">
 <?php //echo $this->form()->openTag($form); ?>
</div>
<div class="form-group">
 <?php  //echo $this->formRow($form->get('id')); ?>
</div>  
<div class="form-group">
 <?php //echo $this->formRow($form->get('nome'));?>
</div>
<div class="form-group">
 <?php //echo $this->formRow($form->get('treino'));?>
</div>
<div class="form-group">
 <?php //echo $this->formRow($form->get('medidas'));?>
</div>
<div class="form-group">
 <?php //echo $this->formRow($form->get('cpf'));?>
</div>
<div class="form-group">
 <?php //echo $this->formRow($form->get('rg'));?>
</div>
<div class="form-group">
 <?php //echo $this->formRow($form->get('dieta'));?>
</div>
<div class="form-group">
 <?php //echo $this->formRow($form->get('email'));?>
</div>
<div class="form-group">
 <?php //echo $this->formRow($form->get('objetivo'));?>
</div>
<div class="form-group">
 
</div>
-->
<?php echo $this->form()->closeTag();?>
