<?php
$form = $this->form;

$form->setAttribute('action',$this->url($this->route,['action'=>'listar']));
$form->prepare();//prepara o formulario

echo "<nav class='navbar navbar-default'>"
. "<div class=\"margin20\">";
echo $this->form()->openTag($form);//abre a tag form com o action
echo $this->formCollection($form);//monta o corpo do formulario
echo $this->form()->closeTag();//fecha formulario
echo "</div></nav>";
?>


<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Alunos</div>


  
  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
          <th>Treino</th>
          <th>Série</th>
          <th>Repeticao</th>
          <th>Intervalo</th>
          <th>Exercicio</th>
      </tr>
      </thead>
      <tbody>
<?php foreach ($this->data as $data): ?>
      <tr> 
        <td><?php echo $data->getIdTreinoGeral()->getNomeTreino(); ?></td>
        <td><?php echo $data->getSerie(); ?></td>
        <td><?php echo $data->getRepeticao(); ?></td>
        <td><?php echo $data->getIntervalo(); ?></td>
        <td><?php echo $data->getIdExercicio()->getNomeExercicio(); ?></td>        
       
        <td>
            <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url($this->route, ['action' => 'editar', 'id' => $data->getIdTreinoExercicio()]); ?>'"class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </button>
             <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url($this->route, ['action' => 'excluir', 'id' => $data->getIdTreinoExercicio()]); ?>'" class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </button>
        </td>      
      </tr>
<?php endforeach; ?>
      </tbody>
   </table>
</div>


<div class="paging">
    <?php 
        $paging = $this->paginationHelper($this->data, $this->page, "/".$this->route."/listar/", $this->data->getDefaultItemCountPerPage()); 
        echo $paging; 
    ?>
</div>