<?php

namespace DoctrineORMModule\Proxy\__CG__\Academia\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TreinoExercicio extends \Academia\Entity\TreinoExercicio implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Academia\\Entity\\TreinoExercicio' . "\0" . 'idTreinoExercicio', '' . "\0" . 'Academia\\Entity\\TreinoExercicio' . "\0" . 'serie', '' . "\0" . 'Academia\\Entity\\TreinoExercicio' . "\0" . 'repeticao', '' . "\0" . 'Academia\\Entity\\TreinoExercicio' . "\0" . 'intervalo', '' . "\0" . 'Academia\\Entity\\TreinoExercicio' . "\0" . 'peso', '' . "\0" . 'Academia\\Entity\\TreinoExercicio' . "\0" . 'idTreinoGeral', '' . "\0" . 'Academia\\Entity\\TreinoExercicio' . "\0" . 'idExercicio');
        }

        return array('__isInitialized__', '' . "\0" . 'Academia\\Entity\\TreinoExercicio' . "\0" . 'idTreinoExercicio', '' . "\0" . 'Academia\\Entity\\TreinoExercicio' . "\0" . 'serie', '' . "\0" . 'Academia\\Entity\\TreinoExercicio' . "\0" . 'repeticao', '' . "\0" . 'Academia\\Entity\\TreinoExercicio' . "\0" . 'intervalo', '' . "\0" . 'Academia\\Entity\\TreinoExercicio' . "\0" . 'peso', '' . "\0" . 'Academia\\Entity\\TreinoExercicio' . "\0" . 'idTreinoGeral', '' . "\0" . 'Academia\\Entity\\TreinoExercicio' . "\0" . 'idExercicio');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TreinoExercicio $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdTreinoExercicio()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdTreinoExercicio();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTreinoExercicio', array());

        return parent::getIdTreinoExercicio();
    }

    /**
     * {@inheritDoc}
     */
    public function getSerie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerie', array());

        return parent::getSerie();
    }

    /**
     * {@inheritDoc}
     */
    public function getRepeticao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepeticao', array());

        return parent::getRepeticao();
    }

    /**
     * {@inheritDoc}
     */
    public function getIntervalo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntervalo', array());

        return parent::getIntervalo();
    }

    /**
     * {@inheritDoc}
     */
    public function getPeso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeso', array());

        return parent::getPeso();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTreinoGeral()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTreinoGeral', array());

        return parent::getIdTreinoGeral();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdExercicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdExercicio', array());

        return parent::getIdExercicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTreinoExercicio($idTreinoExercicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTreinoExercicio', array($idTreinoExercicio));

        return parent::setIdTreinoExercicio($idTreinoExercicio);
    }

    /**
     * {@inheritDoc}
     */
    public function setSerie($serie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerie', array($serie));

        return parent::setSerie($serie);
    }

    /**
     * {@inheritDoc}
     */
    public function setRepeticao($repeticao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRepeticao', array($repeticao));

        return parent::setRepeticao($repeticao);
    }

    /**
     * {@inheritDoc}
     */
    public function setIntervalo($intervalo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntervalo', array($intervalo));

        return parent::setIntervalo($intervalo);
    }

    /**
     * {@inheritDoc}
     */
    public function setPeso($peso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeso', array($peso));

        return parent::setPeso($peso);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTreinoGeral(\Academia\Entity\TreinoGeral $idTreinoGeral)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTreinoGeral', array($idTreinoGeral));

        return parent::setIdTreinoGeral($idTreinoGeral);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdExercicio(\Academia\Entity\Exercicio $idExercicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdExercicio', array($idExercicio));

        return parent::setIdExercicio($idExercicio);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($em)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($em));

        return parent::toArray($em);
    }

}
