<?php

namespace DoctrineORMModule\Proxy\__CG__\Academia\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Login extends \Academia\Entity\Login implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array('email' => NULL);



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        unset($this->email);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', array($name));

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Academia\\Entity\\Login' . "\0" . 'idLogin', 'email', '' . "\0" . 'Academia\\Entity\\Login' . "\0" . 'senha', '' . "\0" . 'Academia\\Entity\\Login' . "\0" . 'idProfissional', '' . "\0" . 'Academia\\Entity\\Login' . "\0" . 'idAdministrador', '' . "\0" . 'Academia\\Entity\\Login' . "\0" . 'idAcademia', '' . "\0" . 'Academia\\Entity\\Login' . "\0" . 'codTipoLogin', '' . "\0" . 'Academia\\Entity\\Login' . "\0" . 'idAluno');
        }

        return array('__isInitialized__', '' . "\0" . 'Academia\\Entity\\Login' . "\0" . 'idLogin', '' . "\0" . 'Academia\\Entity\\Login' . "\0" . 'senha', '' . "\0" . 'Academia\\Entity\\Login' . "\0" . 'idProfissional', '' . "\0" . 'Academia\\Entity\\Login' . "\0" . 'idAdministrador', '' . "\0" . 'Academia\\Entity\\Login' . "\0" . 'idAcademia', '' . "\0" . 'Academia\\Entity\\Login' . "\0" . 'codTipoLogin', '' . "\0" . 'Academia\\Entity\\Login' . "\0" . 'idAluno');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Login $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->email);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdLogin', array());

        return parent::getIdLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdLogin($idLogin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdLogin', array($idLogin));

        return parent::setIdLogin($idLogin);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenha($senha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenha', array($senha));

        return parent::setSenha($senha);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenha', array());

        return parent::getSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProfissional($idProfissional)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProfissional', array($idProfissional));

        return parent::setIdProfissional($idProfissional);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProfissional()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProfissional', array());

        return parent::getIdProfissional();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAdministrador($idAdministrador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAdministrador', array($idAdministrador));

        return parent::setIdAdministrador($idAdministrador);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAdministrador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAdministrador', array());

        return parent::getIdAdministrador();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAcademia(\Academia\Entity\Academia $idAcademia = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAcademia', array($idAcademia));

        return parent::setIdAcademia($idAcademia);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAcademia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAcademia', array());

        return parent::getIdAcademia();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodTipoLogin($codTipoLogin = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodTipoLogin', array($codTipoLogin));

        return parent::setCodTipoLogin($codTipoLogin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodTipoLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodTipoLogin', array());

        return parent::getCodTipoLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAluno(\Academia\Entity\Aluno $idAluno = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAluno', array($idAluno));

        return parent::setIdAluno($idAluno);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAluno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAluno', array());

        return parent::getIdAluno();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayName', array());

        return parent::getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', array());

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayName($displayName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayName', array($displayName));

        return parent::setDisplayName($displayName);
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', array($state));

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($em)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($em));

        return parent::toArray($em);
    }

}
