<?php

namespace DoctrineORMModule\Proxy\__CG__\Academia\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Exercicio extends \Academia\Entity\Exercicio implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Academia\\Entity\\Exercicio' . "\0" . 'idExercicio', '' . "\0" . 'Academia\\Entity\\Exercicio' . "\0" . 'nomeExercicio', '' . "\0" . 'Academia\\Entity\\Exercicio' . "\0" . 'descricao', '' . "\0" . 'Academia\\Entity\\Exercicio' . "\0" . 'idMusculo', '' . "\0" . 'Academia\\Entity\\Exercicio' . "\0" . 'idTreinoGeral');
        }

        return array('__isInitialized__', '' . "\0" . 'Academia\\Entity\\Exercicio' . "\0" . 'idExercicio', '' . "\0" . 'Academia\\Entity\\Exercicio' . "\0" . 'nomeExercicio', '' . "\0" . 'Academia\\Entity\\Exercicio' . "\0" . 'descricao', '' . "\0" . 'Academia\\Entity\\Exercicio' . "\0" . 'idMusculo', '' . "\0" . 'Academia\\Entity\\Exercicio' . "\0" . 'idTreinoGeral');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Exercicio $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdExercicio($idExercicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdExercicio', array($idExercicio));

        return parent::setIdExercicio($idExercicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdExercicio()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdExercicio();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdExercicio', array());

        return parent::getIdExercicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeExercicio($nomeExercicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeExercicio', array($nomeExercicio));

        return parent::setNomeExercicio($nomeExercicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeExercicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeExercicio', array());

        return parent::getNomeExercicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescricao($descricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescricao', array($descricao));

        return parent::setDescricao($descricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricao', array());

        return parent::getDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMusculo(\Academia\Entity\Musculo $idMusculo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMusculo', array($idMusculo));

        return parent::setIdMusculo($idMusculo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMusculo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMusculo', array());

        return parent::getIdMusculo();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdTreinoGeral(\Academia\Entity\TreinoGeral $idTreinoGeral)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdTreinoGeral', array($idTreinoGeral));

        return parent::addIdTreinoGeral($idTreinoGeral);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdTreinoGeral(\Academia\Entity\TreinoGeral $idTreinoGeral)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdTreinoGeral', array($idTreinoGeral));

        return parent::removeIdTreinoGeral($idTreinoGeral);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTreinoGeral()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTreinoGeral', array());

        return parent::getIdTreinoGeral();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($em)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($em));

        return parent::toArray($em);
    }

}
