<?php

namespace DoctrineORMModule\Proxy\__CG__\Academia\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Medidas extends \Academia\Entity\Medidas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Academia\\Entity\\Medidas' . "\0" . 'id', '' . "\0" . 'Academia\\Entity\\Medidas' . "\0" . 'peso', '' . "\0" . 'Academia\\Entity\\Medidas' . "\0" . 'altura', '' . "\0" . 'Academia\\Entity\\Medidas' . "\0" . 'biceps', '' . "\0" . 'Academia\\Entity\\Medidas' . "\0" . 'triceps', '' . "\0" . 'Academia\\Entity\\Medidas' . "\0" . 'peitoralMaior', '' . "\0" . 'Academia\\Entity\\Medidas' . "\0" . 'peitoralMenor', '' . "\0" . 'Academia\\Entity\\Medidas' . "\0" . 'quadril');
        }

        return array('__isInitialized__', '' . "\0" . 'Academia\\Entity\\Medidas' . "\0" . 'id', '' . "\0" . 'Academia\\Entity\\Medidas' . "\0" . 'peso', '' . "\0" . 'Academia\\Entity\\Medidas' . "\0" . 'altura', '' . "\0" . 'Academia\\Entity\\Medidas' . "\0" . 'biceps', '' . "\0" . 'Academia\\Entity\\Medidas' . "\0" . 'triceps', '' . "\0" . 'Academia\\Entity\\Medidas' . "\0" . 'peitoralMaior', '' . "\0" . 'Academia\\Entity\\Medidas' . "\0" . 'peitoralMenor', '' . "\0" . 'Academia\\Entity\\Medidas' . "\0" . 'quadril');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Medidas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeso($peso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeso', array($peso));

        return parent::setPeso($peso);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeso', array());

        return parent::getPeso();
    }

    /**
     * {@inheritDoc}
     */
    public function setAltura($altura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAltura', array($altura));

        return parent::setAltura($altura);
    }

    /**
     * {@inheritDoc}
     */
    public function getAltura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAltura', array());

        return parent::getAltura();
    }

    /**
     * {@inheritDoc}
     */
    public function setBiceps($biceps)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBiceps', array($biceps));

        return parent::setBiceps($biceps);
    }

    /**
     * {@inheritDoc}
     */
    public function getBiceps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBiceps', array());

        return parent::getBiceps();
    }

    /**
     * {@inheritDoc}
     */
    public function setTriceps($triceps)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTriceps', array($triceps));

        return parent::setTriceps($triceps);
    }

    /**
     * {@inheritDoc}
     */
    public function getTriceps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTriceps', array());

        return parent::getTriceps();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeitoralMaior($peitoralMaior)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeitoralMaior', array($peitoralMaior));

        return parent::setPeitoralMaior($peitoralMaior);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeitoralMaior()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeitoralMaior', array());

        return parent::getPeitoralMaior();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeitoralMenor($peitoralMenor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeitoralMenor', array($peitoralMenor));

        return parent::setPeitoralMenor($peitoralMenor);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeitoralMenor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeitoralMenor', array());

        return parent::getPeitoralMenor();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuadril($quadril)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuadril', array($quadril));

        return parent::setQuadril($quadril);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuadril()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuadril', array());

        return parent::getQuadril();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
