<?php
/*
 * @var $form \Zend\Form\Form
 */
 $title = 'Cadastrar Musculo';
 echo $this->headTitle($title);
 echo "<h1 style='text-align:center'>$title</h1>";
$form = $this->form;

//informa se existir erros no formulario
$flash = $this->flashMessenger();
 $flash->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
     ->setMessageSeparatorString('</li><li>')
     ->setMessageCloseString('</li></ul></div>');

 echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
 echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
 echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
 echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
 
//seta action, para onde o formulario será enviar o formulario
$form->setAttribute('action',$this->url($this->route,['action'=>'inserir']));
$form->prepare();//prepara o formulario
echo $this->form()->openTag($form);//abre a tag form com o action
echo $this->form($form);//monta o corpo do formulario
echo $this->form()->closeTag();//fecha formulario

/*
$form->setAttribute('action',$this->url('cadastrarAluno',['action'=>'inserir']))
      ->prepare();

 echo $this->form()->openTag($form);

 $product = $form->get('aluno');

 echo $this->formRow($product->get('nome'));
 echo $this->formRow($product->get('cpf'));
 echo $this->formCollection($product->get('endereco'));

 $brand = $product->get('endereco');

 echo $this->formRow($brand->get('rua'));

 echo $this->formHidden($form->get('csrf'));
 echo $this->formElement($form->get('submit'));

 echo $this->form()->closeTag();
*/
 ?>

