<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Alunos</div>

  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
          <th>Nome</th>
          <th>RG</th>
          <th>CPF</th>
          <th>Email</th>
      </tr>
      </thead>
      <tbody
<?php foreach ($this->data as $aluno): ?>
      <tr> 
        <td><?php echo $aluno->getNome(); ?></td>
        <td><?php echo $aluno->getRg(); ?></td>
        <td><?php echo $aluno->getCpf(); ?></td>
        <td><?php echo $aluno->getEmail(); ?></td>
       
      </tr>
<?php endforeach; ?>
      </tbody>
   </table>
</div>