<?php //echo var_dump($retorno);?>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Academias</div>

  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
          <th>Nome</th>
          <th>Data de Presença</th>
      </tr>
      </thead>
      <tbody
<?php 
//echo var_dump($this->data);
foreach ($this->data as $data): ?>
      <?php
        
      ?>
      <tr> 
        <td><?php echo $data->getIdAluno()->getNomeAluno();?></td>     
        <td><?php echo date_format($data->getDataPresenca(),'d/m/Y'); ?></td>     
        <td><?php //echo $data->getDataCadastro(); ?></td> 
         <td>
            <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('medida', ['action' => 'editar', 'id' => $data->getIdFrequenciaAluno()]); ?>'"class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </button>
        </td>     
      </tr>
<?php endforeach; ?>
      </tbody>
   </table>
</div>

<div class="paging">
    <?php 
        $paging = $this->paginationHelper($this->data, $this->page, "/academia/listar/", $this->data->getDefaultItemCountPerPage()); 
        echo $paging; 
    ?>
</div>