<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Dietas</div>

  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
          <th>Dieta</th>
          <th>Alimento</th>          
      </tr>
      </thead>
      <tbody
<?php foreach ($this->data as $data): ?>
      <tr> 
        <td><?php echo $data->getIdDietaGeral()->getNomeDieta(); ?></td>
        <td><?php echo $data->getIdAlimento()->getNomeAlimento(); ?></td>
         <td>
            <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url($this->route, ['action' => 'editar', 'id' => $data->getIdDietaAlimento()]); ?>'"class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </button>
             <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url($this->route, ['action' => 'excluir', 'id' => $data->getIdDietaAlimento()]); ?>'" class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </button>
        </td>     
      </tr>
<?php endforeach; ?>
      </tbody>
   </table>
</div>

<div class="paging">
    <?php 
        $paging = $this->paginationHelper($this->data, $this->page, "/".$this->route."/listar/", $this->data->getDefaultItemCountPerPage()); 
        echo $paging; 
    ?>
</div>