<?php

 $title = 'Exercicio';
 $this->headTitle($title);
$form = $this->form;
 ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php 
//informa se existir erros no formulario
$flash = $this->flashMessenger();
 $flash->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
     ->setMessageSeparatorString('</li><li>')
     ->setMessageCloseString('</li></ul></div>');

 echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
 echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
 echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
 echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
 
//seta action, para onde o formulario será enviar o formulario
$form->setAttribute('action',$this->url('exercicio',['action'=>'editar','id' => $this->id]));
$form->prepare();//prepara o formulario
echo $this->form()->openTag($form);//abre a tag form com o action
echo $this->formCollection($form);//monta o corpo do formulario
echo $this->form()->closeTag();//fecha formulario

?>
