<?php //echo var_dump($retorno);?>
<h1 class="text-center">Consultar Academias</h1>

<nav class="navbar navbar-default ">
<form class="margin20" method="POST">
  <fieldset>
    <div class="form-group">
      <label for="disabledTextInput">Nome</label>
      <input type="text" id="nome" name="nome" class="form-control" placeholder="Digite o nome">
    </div>
      <div class="form-group">
      <label for="disabledTextInput">Data de Cadastro</label>
      <br/>
      De: <input type="date" id="data_cadastro_de" name="data_cadastro_de" s class="form-control" placeholder="">
      Ate: <input type="date" id="data_cadastro_ate" name="data_cadastro_ate" class="form-control" placeholder="">
    </div>
    <button type="submit" class="btn btn-primary">Filtrar</button>
  </fieldset>
</form>
</nav>

<div class="panel panel-default">
  <!-- Default panel contents -->
  
  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
          <th>Nome</th>
          <th>Cadastro</th>
      </tr>
      </thead>
      <tbody
<?php 
//echo var_dump($this->data);
foreach ($this->data as $data): ?>
      <tr> 
        <td><?php echo $data->getNome(); ?></td>     
        <td><?php //echo $data->getDataCadastro(); ?></td> 
         <td>
            <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('academia', ['action' => 'editar', 'id' => $data->getIdAcademia()]); ?>'"class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </button>
             <button type="button" onclick="confirmarExclusao('<?php echo $this->url('academia', ['action' => 'excluir', 'id' => $data->getIdAcademia()]); ?>')" class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </button>
        </td>     
      </tr>
<?php endforeach; ?>
      </tbody>
   </table>
</div>

<div class="paging">
    <?php 
        $paging = $this->paginationHelper($this->data, $this->page, "/academia/listar/", $this->data->getDefaultItemCountPerPage()); 
        echo $paging; 
    ?>
</div>