<h1 class="text-center">Consultar Dietas</h1>
<nav class="navbar navbar-default ">
<form class="margin20" method="POST">
  <fieldset>
    <div class="form-group">
      <label for="disabledTextInput">Nome da Dieta</label>
      <input type="text" id="nome" name="nome" class="form-control" placeholder="Digite o nome">
    </div>
   
    <button type="submit" class="btn btn-primary">Filtrar</button>
  </fieldset>
</form>
</nav>

<div class="panel panel-default">
  <!-- Default panel contents -->
  

  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
          <th>Nome</th>
          <th>Finalidade</th>
          <th>Academia</th>
      </tr>
      </thead>
      <tbody
<?php foreach ($this->data as $data): ?>
      <tr> 
        <td><?php echo $data->getNomeDieta(); ?></td>
        <td><?php echo $data->getIdFinalidade()->getFinalidade(); ?></td>
        <td><?php echo $data->getIdAcademia()->getNome(); ?></td>        
         <td>
            <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url($this->route, ['action' => 'editar', 'id' => $data->getIdDietaGeral()]); ?>'"class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </button>
             <button type="button" onclick="confirmarExclusao('<?php echo $this->url($this->route, ['action' => 'excluir', 'id' => $data->getIdDietaGeral()]); ?>')" class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </button>
        </td>     
      </tr>
<?php endforeach; ?>
      </tbody>
   </table>
</div>

<div class="paging">
    <?php 
        $paging = $this->paginationHelper($this->data, $this->page, "/dieta/listar/", $this->data->getDefaultItemCountPerPage()); 
        echo $paging; 
    ?>
</div>