<?php
/*
 * @var $form \Zend\Form\Form
 */
 $title = 'Cadastrar Aluno';
 echo $this->headTitle($title);
 echo "<h1 style='text-align:center'>$title</h1>";
$form = $this->form;

//se tiver logado com usuario, seta para disable
if($this->zfcUserIdentity()->getIdAluno() != null){
    $form->getElements()['cpfAluno']->setAttribute("disabled","true");
    $form->getElements()['rgAluno']->setAttribute("disabled","true");
    $form->getElements()['nomeAluno']->setAttribute("disabled","true");
    $form->getElements()['sobrenomeAluno']->setAttribute("disabled","true");
}

//informa se existir erros no formulario
$flash = $this->flashMessenger();
 $flash->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
     ->setMessageSeparatorString('</li><li>')
     ->setMessageCloseString('</li></ul></div>');

 echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
 echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
 echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
 echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
 
//seta action, para onde o formulario será enviar o formulario
$form->setAttribute('action',$this->url('aluno',['action'=>'editar','id' => $this->id]));

$form->prepare();//prepara o formulario
echo $this->form()->openTag($form);//abre a tag form com o action
echo $this->formCollection($form);//monta o corpo do formulario
echo $this->form()->closeTag();//fecha formulario

include("webcan-foto-perfil.php");
 ?>
