<div class="backgroundTreino">
    
<?php foreach ($this->data as $aluno): 
    if($aluno->getArquivo() != null){
         $foto = stream_get_contents($aluno->getArquivo());
    }else{
        $foto = "";
    }
?>

<div class="row">
    <div class="col-sm-4">
        <div class="box">
            <div class="foto text-center">
                <img src="<?php echo $foto; ?>" width="150" height="150" style="border-radius: 50%">;
            </div>
            <ul class="list-group  text-center">
                <li class="list-group-item"><?php echo $aluno->getNomeAluno(); ?></li>
                <li class="list-group-item">RG: <?php echo $aluno->getRgAluno(); ?></li>
                <li class="list-group-item">CPF: <?php echo $aluno->getCpfAluno(); ?></li>    
                <li class="list-group-item">Email: <?php echo "<a href='mailto:".$aluno->getIdLogin()->getEmail()."'>".$aluno->getIdLogin()->getEmail()."</a>"; ?></li>
            </ul>
            <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('aluno', ['action' => 'editar', 'id' => $aluno->getIdAluno()]); ?>'" class="btn btn-default pull-right" aria-label="Left Align">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </button>
        </div>       
    </div>   
    <div class="col-sm-4">
        <div class="box2 text-center" onclick="javascript:window.location.href = '<?php echo $this->url('treino', ['action' => 'getTreinoAluno', 'id' => $aluno->getIdAluno()]); ?>'">
            <i class="glyphicon glyphicon-list-alt"></i>
            <h2>Treinos</h2>
        </div>
        <div class="box2 text-center" onclick="javascript:window.location.href = '<?php echo $this->url('dietaAluno',array('action' => 'getDietaAluno', 'id' => $aluno->getIdAluno())); ?>'">
            <i class="glyphicon glyphicon-cutlery"></i>
            <h2>Dietas</h2>
        </div>
    </div>
</div>       



<?php endforeach; ?>
</div>