<h1 class="text-center">Consultar Alunos</h1>
<?php 

//informa se existir erros no formulario
$flash = $this->flashMessenger();
 $flash->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
     ->setMessageSeparatorString('</li><li>')
     ->setMessageCloseString('</li></ul></div>');

 echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
 echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
 echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
 echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
 ?>

<nav class="navbar navbar-default ">
<form class="margin20" method="POST">
  <fieldset>
    <div class="form-group">
      <label for="disabledTextInput">Nome</label>
      <input type="text" id="nome" name="nome" class="form-control" placeholder="Digite o nome">
    </div>
    <div class="form-group">
      <label for="disabledTextInput">CPF</label>
      <input type="text" id="cpf" name="cpf" class="form-control" placeholder="Digite o cpf">
    </div>
    <button type="submit" class="btn btn-primary">Filtrar</button>
  </fieldset>
</form>
</nav>

<div class="panel panel-default">
  <!-- Default panel contents -->
  


  
  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
          <th>Nome</th>
          <th>RG</th>
          <th>CPF</th>
          <th>Email</th>
          <th>Ação</th>
      </tr>
      </thead>
      <tbody>
<?php foreach ($this->data as $aluno): ?>
      <tr> 
        <td><?php echo $aluno->getNomeAluno(); ?></td>
        <td><?php echo $aluno->getRgAluno(); ?></td>
        <td><?php echo $aluno->getCpfAluno(); ?></td>
        <td><?php echo "<a href='mailto:".$aluno->getIdLogin()->getEmail()."'>".$aluno->getIdLogin()->getEmail()."</a>"; ?></td>
       
        <td>
            <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('aluno', ['action' => 'editar', 'id' => $aluno->getIdAluno()]); ?>'"class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </button>
             <button type="button" onclick="confirmarExclusao('<?php echo $this->url('aluno', ['action' => 'excluir', 'id' => $aluno->getIdAluno()]); ?>')" class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </button>
        </td>      
      </tr>
<?php endforeach; ?>
      </tbody>
   </table>
</div>


<div class="paging">
    <?php 
        $paging = $this->paginationHelper($this->data, $this->page, "/aluno/listar/", $this->data->getDefaultItemCountPerPage()); 
        echo $paging; 
    ?>
</div>