<?php

namespace DoctrineORMModule\Proxy\__CG__\Academia\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Treino extends \Academia\Entity\Treino implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Academia\\Entity\\Treino' . "\0" . 'id', '' . "\0" . 'Academia\\Entity\\Treino' . "\0" . 'nome', '' . "\0" . 'Academia\\Entity\\Treino' . "\0" . 'dataCadastro', '' . "\0" . 'Academia\\Entity\\Treino' . "\0" . 'dataInicio', '' . "\0" . 'Academia\\Entity\\Treino' . "\0" . 'dataFim', '' . "\0" . 'Academia\\Entity\\Treino' . "\0" . 'exercicios');
        }

        return array('__isInitialized__', '' . "\0" . 'Academia\\Entity\\Treino' . "\0" . 'id', '' . "\0" . 'Academia\\Entity\\Treino' . "\0" . 'nome', '' . "\0" . 'Academia\\Entity\\Treino' . "\0" . 'dataCadastro', '' . "\0" . 'Academia\\Entity\\Treino' . "\0" . 'dataInicio', '' . "\0" . 'Academia\\Entity\\Treino' . "\0" . 'dataFim', '' . "\0" . 'Academia\\Entity\\Treino' . "\0" . 'exercicios');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Treino $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCadastro($dataCadastro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCadastro', array($dataCadastro));

        return parent::setDataCadastro($dataCadastro);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCadastro', array());

        return parent::getDataCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataInicio($dataInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataInicio', array($dataInicio));

        return parent::setDataInicio($dataInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataInicio', array());

        return parent::getDataInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataFim($dataFim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataFim', array($dataFim));

        return parent::setDataFim($dataFim);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataFim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataFim', array());

        return parent::getDataFim();
    }

    /**
     * {@inheritDoc}
     */
    public function addExercicio(\Academia\Entity\Exercicios $exercicios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExercicio', array($exercicios));

        return parent::addExercicio($exercicios);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExercicio(\Academia\Entity\Exercicios $exercicios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExercicio', array($exercicios));

        return parent::removeExercicio($exercicios);
    }

    /**
     * {@inheritDoc}
     */
    public function getExercicios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExercicios', array());

        return parent::getExercicios();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
