<?php //echo var_dump($retorno);?>
<h1 class="text-center">Distância Percorrida</h1>
<div class="panel panel-default">
  <!-- Default panel contents -->
  

  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
          <th>Aluno</th>
          <th>Tempo (minutos)</th>
          <th>Distância (metros)</th>
          <th>Competência</th>
          <th>Calorias Gastas (kcal)</th>
      </tr>
      </thead>
      <tbody>
<?php 
//echo var_dump($this->data);
foreach ($this->data as $data): ?>
      <tr> 
        <td><?php echo $data->getIdAluno()->getNomeAluno(); ?></td>     
        <td><?php echo $data->getTempo(); ?></td> 
        <td><?php echo $data->getDistancia(); ?></td> 
        <td><?php echo date('d/m/Y',strtotime($data->getCompetencia())); ?></td> 
        <td><?php echo $data->getCalorias(); ?></td> 
      </tr>
<?php endforeach; ?>
      </tbody>
   </table>
</div>

<div class="paging">
    <?php 
        $paging = $this->paginationHelper($this->data, $this->page, "/atividade/listar/", $this->data->getDefaultItemCountPerPage()); 
        echo $paging; 
    ?>
</div>