<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Dietas</div>

  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
          <th>Nome</th>
          <th>Finalidade</th>
          <th>Data Inicio</th>
          <th>Data Fim</th>
          <th>Objetivo</th>
      </tr>
      </thead>
      <tbody
<?php foreach ($this->data as $data): ?>
      <tr> 
        <td><?php echo $data['nome']; ?></td>
        <td><?php echo $data['finalidade']; ?></td>
        <td><?php echo $data['dataInicio']; ?></td>
        <td><?php echo $data['dataFim']; ?></td>   
         <td>
            <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('dieta', ['action' => 'editar', 'id' => $data['id']]); ?>'"class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </button>
             <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('dieta', ['action' => 'excluir', 'id' => $data['id']]); ?>'" class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </button>
        </td>     
      </tr>
<?php endforeach; ?>
      </tbody>
   </table>
</div>

<div class="paging">
    <?php 
        $paging = $this->paginationHelper($this->data, $this->page, "/dieta/listar/", $this->data->getDefaultItemCountPerPage()); 
        echo $paging; 
    ?>
</div>