<nav class="navbar navbar-default ">
<form class="margin20" method="POST">
  <fieldset>
    <div class="form-group">
      <label for="disabledTextInput">Nome</label>
      <input type="text" id="nome" name="nome" class="form-control" placeholder="Digite o nome do alimento.">
    </div>
    
    <button type="submit" class="btn btn-primary">Filtrar</button>
  </fieldset>
</form>
</nav>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Alimentos</div>

  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
            <th>Academia</th>
            <th>Nome</th>
            <th>Caracteristica</th>          
      </tr>
      </thead>
      <tbody
<?php foreach ($this->data as $data): ?>
      <tr> 
        <td><?php if($data->getIdAcademia() == null){echo "Todas";}else{echo $data->getIdAcademia()->getNome();} ?></td>  
        <td><?php echo $data->getNomeAlimento(); ?></td>  
        <td><?php echo $data->getDescricao(); ?></td>     
        <td>
            <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('alimento', ['action' => 'editar', 'id' => $data->getIdAlimento()]); ?>'"class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </button>
             <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('alimento', ['action' => 'excluir', 'id' => $data->getIdAlimento()]); ?>'" class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </button>
        </td>        
      </tr>
<?php endforeach; ?>
      </tbody>
   </table>
</div>

<div class="paging">
    <?php 
        $paging = $this->paginationHelper($this->data, $this->page, "/alimento/listar/", $this->data->getDefaultItemCountPerPage()); 
        echo $paging; 
    ?>
</div>