
<nav class="navbar navbar-default ">
<form class="margin20" method="POST">
  <fieldset>
    <div class="form-group">
      <label for="disabledTextInput">Nome</label>
      <input type="text" id="nome" name="nome" class="form-control" placeholder="Digite o nome">
    </div>
    <div class="form-group">
      <label for="disabledTextInput">Data de Inicio</label>
      <br/>
      De: <input type="date" id="data_cadastro_de" name="data_inicio_de" s class="form-control" placeholder="">
      Ate: <input type="date" id="data_cadastro_ate" name="data_inicio_ate" class="form-control" placeholder="">
    </div>
    <button type="submit" class="btn btn-primary">Filtrar</button>
  </fieldset>
</form>
</nav>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Treinos</div>

  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
          <th>Nome</th>
          <th>Inicio</th>
          <th>Fim</th>
      </tr>
      </thead>
      <tbody
<?php foreach ($this->data as $data): ?>
      <tr> 
        <td><?php echo $data->getNome(); ?></td>    
        <td><?php echo date_format($data->getDataInicio(), 'd/m/Y'); ?></td>    
        <td><?php echo date_format($data->getDataFim(), 'd/m/Y'); ?></td>
        <td>
            <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('treino', ['action' => 'editar', 'id' => $data->getId()]); ?>'"class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </button>
             <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('treino', ['action' => 'excluir', 'id' => $data->getId()]); ?>'" class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </button>
        </td>     
      </tr>
<?php endforeach; ?>
      </tbody>
   </table>
</div>

<div class="paging">
    <?php 
        $paging = $this->paginationHelper($this->data, $this->page, "/treino/listar/", $this->data->getDefaultItemCountPerPage()); 
        echo $paging; 
    ?>
</div>

