<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Treinos</div>

  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
          <th>Nome</th>
          <th>Inicio</th>
          <th>Fim</th>
      </tr>
      </thead>
      <tbody
<?php foreach ($this->data as $data): ?>
      <tr> 
        <td><?php echo $data->getNome(); ?></td>    
        <td><?php echo date_format($data->getDataInicio(), 'd/m/Y'); ?></td>    
        <td><?php echo date_format($data->getDataFim(), 'd/m/Y'); ?></td>
        <td>
            <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('cadastrarTreino', ['action' => 'editar', 'id' => $data->getId()]); ?>'"class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </button>
             <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('cadastrarTreino', ['action' => 'excluir', 'id' => $data->getId()]); ?>'" class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </button>
        </td>     
      </tr>
<?php endforeach; ?>
      </tbody>
   </table>
</div>