<?php 
    echo $this->doctype();
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Academia '. $this->translate('Workout'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/jquery.dataTables.min.css'))
                        ->prependStylesheet($this->basePath('css/responsive.dataTables.min.css'));
        ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
//            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
//            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath('js/javascript_geral.js',$type = 'text/javascript', $attrs = array()))
//            ->appendFile($this->basePath('lib/jquery-ui-1.11.4.custom/jquery-ui.min.js',$type = 'text/javascript', $attrs = array()))
            ->appendFile($this->basePath('js/jquery.dataTables.min.js',$type = 'text/javascript', $attrs = array()))
            ->appendFile($this->basePath('js/dataTables.responsive.min.js',$type = 'text/javascript', $attrs = array()))
            ->appendFile($this->basePath('js/charts_loader.js',$type = 'text/javascript', $attrs = array()))
            
            
                
               
        ?>

    </head>
    <body>
        <?php
            
            if($this->zfcUserIdentity()){ 
                if(!empty($this->zfcUserIdentity()->getIdAluno())){//se for login do aluno
                    $menu = "menuAluno.php";
                    $usuario = "Aluno - ".$this->zfcUserIdentity()->getIdAluno()->getNomeAluno();
                }else if(!empty($this->zfcUserIdentity()->getIdProfissional())){//se for login do profissional
                    $menu = "menuProfissional.php";
                    $usuario = "Profissional - ".$this->zfcUserIdentity()->getIdProfissional()->getNome();
                }else if(!empty($this->zfcUserIdentity()->getIdAcademia())){//se for login da academia
                    $menu = "menuAcademia.php";
                    $usuario = "Academia - ".$this->zfcUserIdentity()->getIdAcademia()->getNome();
                }else if(!empty($this->zfcUserIdentity()->getIdAdministrador())){
                    $menu = "menu.php";
                    $usuario = "Administrador";
                }
        ?>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" style="color: orange" href="<?php echo $this->url('home') ?>">
                        
                        
                        <img src="/img/logo-academia.png"/>
                        &nbsp;<?php echo $this->translate('Workout | '.$usuario);  ?>
                        
                    </a>
					
                </div>
                <div class="collapse navbar-collapse">
                   <?php 
                        
                        include($menu); 
                   ?>
                </div><!--/.nav-collapse -->
            </div>
			
        </nav>
        <?php } ?>
        <div class="container">
            <?php echo  $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2015 - <?php echo date('Y') ?> by Workout. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php 
//            echo $this->inlineScript();
        ?>
    </body>
</html>