<?php

 $title = 'Frequência';
 $this->headTitle($title);

 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 
 <?php
 //informa se existir erros no formulario
$flash = $this->flashMessenger();
 $flash->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
     ->setMessageSeparatorString('</li><li>')
     ->setMessageCloseString('</li></ul></div>');

 echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
 echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
 echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
 echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
// echo var_dump($this->form());
/* $form->setAttribute('action', $this->url('cadastrarAluno', array('action' => 'add')));
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->formCollection($form);
  
  
 */
 
 
?>

<!--
<div class="form-group">
 <?php //echo $this->form()->openTag($form); ?>
</div>
<div class="form-group">
 <?php  //echo $this->formRow($form->get('id')); ?>
</div>  
<div class="form-group">
 <?php //echo $this->formRow($form->get('nome'));?>
</div>
<div class="form-group">
 <?php //echo $this->formRow($form->get('treino'));?>
</div>
<div class="form-group">
 <?php //echo $this->formRow($form->get('medidas'));?>
</div>
<div class="form-group">
 <?php //echo $this->formRow($form->get('cpf'));?>
</div>
<div class="form-group">
 <?php //echo $this->formRow($form->get('rg'));?>
</div>
<div class="form-group">
 <?php //echo $this->formRow($form->get('dieta'));?>
</div>
<div class="form-group">
 <?php //echo $this->formRow($form->get('email'));?>
</div>
<div class="form-group">
 <?php //echo $this->formRow($form->get('objetivo'));?>
</div>
<div class="form-group">
 
</div>
-->
<?php $form->prepare(); ?>
<?php echo $this->form($this->form); ?>
<?php echo $this->form()->closeTag();?>
