<h1 class="text-center">Frequência</h1>
<?php
$form = $this->form;
$form->setAttribute('action',$this->url($this->route,['action'=>'listar']));
$form->prepare();//prepara o formulario

echo "<nav class='navbar navbar-default'>"
. "<div class=\"margin20\">";
echo $this->form()->openTag($form);//abre a tag form com o action
echo $this->formCollection($form);//monta o corpo do formulario
echo $this->form()->closeTag();//fecha formulario
echo "</div></nav>";
?>

<div class="panel panel-default">
  <!-- Default panel contents -->
  
  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
          <th>Aluno</th>
          <th>Data de Presença</th>
          
      </tr>
      </thead>
      <tbody>
<?php foreach ($this->data as $data): ?>
      <tr> 
          <td><?php echo $data->getIdAluno()->getNomeAluno(); ?></td>       
        <td><?php echo date_format($data->getDataPresenca(),'d/m/Y'); ?></td>
        
          
      </tr>
<?php endforeach; ?>
      </tbody>
   </table>
</div>


<div class="paging">
    <?php 
        $paging = $this->paginationHelper($this->data, $this->page, "/".$this->route."/listar/", $this->data->getDefaultItemCountPerPage()); 
        echo $paging; 
    ?>
</div>