<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Medidas</div>

  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
          <th>Peso</th>
          <th>Altura</th>
          <th>Peitoral Maior</th>
          <th>Peitoral Menor</th>
          <th>Quadril</th>
          <th>Biceps Esq.</th>
          <th>Biceps Dir.</th>
          <th>Triceps Esq.</th>
          <th>Triceps Dir.</th>
          <th>Quadril Esq.</th>
          <th>Quadril Dir.</th>
      </tr>
      </thead>
      <tbody
<?php foreach ($this->data as $data): ?>
      <tr> 
        <td><?php echo $data->getPeso(); ?></td>  
        <td><?php echo $data->getAltura(); ?></td>   
        <td><?php echo $data->getPeitoralMaior(); ?></td>   
        <td><?php echo $data->getPeitoralMenor(); ?></td>   
        <td><?php echo $data->getQuadril(); ?></td>   
        <td><?php echo $data->getBicepsEsquerdo(); ?></td>   
        <td><?php echo $data->getBicepsDireito(); ?></td>   
        <td><?php echo $data->getTricepsEsquerdo(); ?></td>   
        <td><?php echo $data->getTricepsDireito(); ?></td>   
        <td><?php echo $data->getCoxasEsquerda(); ?></td>   
        <td><?php echo $data->getPanturrilhaEsquerda(); ?></td>   
        <td><?php echo $data->getPanturrilhaDireita(); ?></td>   
        <td><?php echo $data->getQuadrilEsquerdo(); ?></td>   
        <td><?php echo $data->getQuadrilDireito(); ?></td>  
        <td>
            <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('cadastrarMedida', ['action' => 'editar', 'id' => $data->getId()]); ?>'"class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </button>
             <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('cadastrarMedida', ['action' => 'excluir', 'id' => $data->getId()]); ?>'" class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </button>
        </td>        
      </tr>
<?php endforeach; ?>
      </tbody>
   </table>
</div>