<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Medidas</div>

  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
          <th>Aluno</th>
          <th>Peso</th>
          <th>Altura</th>
          <th>Peitoral Maior</th>
          <th>Peitoral Menor</th>
      </tr>
      </thead>
      <tbody
<?php foreach ($this->data as $data): ?>
      <tr> 
        <td><?php echo $data->getIdAluno()->getNomeAluno(); ?></td>  
        <td><?php echo $data->getPeso(); ?></td>  
        <td><?php echo $data->getAltura(); ?></td>   
        <td><?php echo $data->getPeitoralMaior(); ?></td>   
        <td><?php echo $data->getPeitoralMenor(); ?></td> 
        <td>
            <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('medida', ['action' => 'editar', 'id' => $data->getIdMedida()]); ?>'"class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </button>
             <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('medida', ['action' => 'excluir', 'id' => $data->getIdMedida()]); ?>'" class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </button>
        </td>        
      </tr>
<?php endforeach; ?>
      </tbody>
   </table>
</div>

<div class="paging">
    <?php 
        $paging = $this->paginationHelper($this->data, $this->page, "/medida/listar/", $this->data->getDefaultItemCountPerPage()); 
        echo $paging; 
    ?>
</div>