<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Profissionais</div>

  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
          <th>Nome</th>
          <th>RG</th>
          <th>CPF</th>
      </tr>
      </thead>
      <tbody
<?php foreach ($this->data as $profissional): ?>
      <tr> 
        <td><?php echo $profissional->getNome(); ?></td>
        <td><?php echo $profissional->getRg(); ?></td>
        <td><?php echo $profissional->getCpf(); ?></td>
        
        <td>
            <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('profissional', ['action' => 'editar', 'id' => $profissional->getId()]); ?>'"class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </button>
             <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('profissional', ['action' => 'excluir', 'id' => $profissional->getId()]); ?>'" class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </button>
        </td>      
      </tr>
<?php endforeach; ?>
      </tbody>
   </table>
</div>

<div class="paging">
    <?php 
        $paging = $this->paginationHelper($this->data, $this->page, "/profissional/listar/", $this->data->getDefaultItemCountPerPage()); 
        echo $paging; 
    ?>
</div>