<?php

 $title = 'Cadastrar Profissional';
 $this->headTitle($title);

 ?>
<h1 class="text-center"><?php echo $this->escapeHtml($title); ?></h1>
<?php 
//informa se existir erros no formulario
$flash = $this->flashMessenger();
 $flash->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
     ->setMessageSeparatorString('</li><li>')
     ->setMessageCloseString('</li></ul></div>');

 echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
 echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
 echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
 echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
 
$form->prepare();
echo $this->form($this->form); 
echo $this->form()->closeTag();

?>
