<nav class="navbar navbar-default ">
<form class="margin20" method="POST">
  <fieldset>
    <div class="form-group">
      <label for="disabledTextInput">Nome</label>
      <input type="text" id="nome" name="nome" class="form-control" placeholder="Digite o nome">
    </div>
    <div class="form-group">
      <label for="disabledTextInput">Usuario</label>
      <input type="text" id="usuario" name="usuario" class="form-control" placeholder="Digite o usuario">
    </div>
    <button type="submit" class="btn btn-primary">Filtrar</button>
  </fieldset>
</form>
</nav>


<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Profissionais</div>

  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
          <th>Nome</th>
      </tr>
      </thead>
      <tbody
<?php foreach ($this->data as $profissional): ?>
      <tr> 
        <td><?php echo $profissional->getNome(); ?></td>
        
        <td>
            <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('profissional', ['action' => 'editar', 'id' => $profissional->getId()]); ?>'"class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </button>
             <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('profissional', ['action' => 'excluir', 'id' => $profissional->getId()]); ?>'" class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </button>
        </td>      
      </tr>
<?php endforeach; ?>
      </tbody>
   </table>
</div>

<div class="paging">
    <?php 
        $paging = $this->paginationHelper($this->data, $this->page, "/profissional/listar/", $this->data->getDefaultItemCountPerPage()); 
        echo $paging; 
    ?>
</div>