<h1 class="text-center">Consultar Dietas x Alunos</h1>
<div class="panel panel-default">
  <!-- Default panel contents -->
 
  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
          <th>Aluno</th>
          <th>Dieta</th>
          <th>Data Inicio</th>
          <th>Data Fim</th>
      </tr>
      </thead>
      <tbody
<?php foreach ($this->data as $data): 
    ?>
      <tr> 
        <td><?php echo $data->getIdAluno()->getNomeAluno(); ?></td>
        <td><?php echo $data->getIdDietaGeral()->getNomeDieta(); ?></td>
        <td><?php if($data->getDataIniVig() != null){echo date_format($data->getDataIniVig(),'d/m/Y');} ?></td>
        <td><?php if($data->getDataFimVig() != null){echo date_format($data->getDataFimVig(),'d/m/Y');} ?></td>
        
         <td>
            <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url($this->route, ['action' => 'editar', 'id' => $data->getIdDietaAluno()]); ?>'"class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </button>
             <button type="button" onclick="confirmarExclusao('<?php echo $this->url($this->route, ['action' => 'excluir', 'id' => $data->getIdDietaAluno()]); ?>')" class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </button>
        </td>     
      </tr>
<?php endforeach; ?>
      </tbody>
   </table>
</div>

<div class="paging">
    <?php 
        $paging = $this->paginationHelper($this->data, $this->page, "/".$this->route."/listar/", $this->data->getDefaultItemCountPerPage()); 
        echo $paging; 
    ?>
</div>