
<img width="100%" style="position: relative; top: -10px;" src="<?php echo $this->basePath('img/banner.png'); ?>">
<!--
<div class="jumbotron">
    É dono de uma academia e ainda não possuí um sistema de qualidade? Acompanhe de perto seus alunos e diminua seu esforço de trabalho, com esse sofisticado sistema de acompanhamento de treinos.
    Tenha relatórios de desempenho de seus alunos, dispare avisos para cada um deles, cadastre os treinos e dietas para cada um. Saiba o quanto seu aluno está desenvolvendo através de relatórios e muito mais.
</div>
-->
<div class="row ">

    <div class="col-md-8">
        <div class="panel panel-default minHeight200">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-phone"></span>&nbsp;&nbsp; <?php echo $this->translate('Android') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Faça o download do aplicativo Workout e acompanhe seus treinos, receba dicas de dietas e treinos, pratique atividades físicas e seja acompanhado por esse incrível aplicativo!')); ?></p>
                <p><a class="btn btn-default pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('Download') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default minHeight200">
            <div class="panel-heading">
                
                <h3 class="panel-title"><span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;<?php echo $this->translate('Login') ?></h3>
            </div>
            <div class="panel-body">
                <form id="login-form" action="<?php echo $this->url('login',array('action' => 'login')) ?>" method="post" role="form" style="display: block;">
                    <div class="form-group "><input type="text" name="usuario" placeholder="usuario" class="form-control" value=""></div>
                    <div class="form-group "><input type="password" name="senha" placeholder="senha" class="form-control" value=""></div>
                    <div class="form-group">
                        <div class="row">
                                <div class="col-sm-4 pull-right">
                                        <input type="submit" name="login-submit"  tabindex="4" class="form-control btn btn-primary " value="Entrar">
                                </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

   
</div>
