<style type="text/css">
    body{
        background: url('http://localhost/site/wp-content/themes/sydney/images/2.jpg');
    } 
    
    footer p{
        color: #CCC;
    }
    
    img{
        max-width: 100%;
    }
    
    .logo{
        cursor: pointer;
    }
</style>
<link href='http://fonts.googleapis.com/css?family=Raleway:500' rel='stylesheet' type='text/css'>

<?php if(!(empty($loginmsg))):?>
<div class="alert alert-danger" role="alert"><?php echo $loginmsg;?></div>
<?php endif; ?>
 
 

<div class="container ">
    <div class="page-header">
        <h1 onclick="window.location.href='site'" class="logo">Workout <small> System</small></h1>
    </div>    
    <?php 
    if(!$this->identity()){ ?>
        <div class="row">
            <div class="col-md-5 col-md-offset-3">
                <div class="middlePage">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                          <h3 class="panel-title">Login</h3>
                        </div>
                        <div class="panel-body">
                           
                            <div class="row">
                                <!--div class="col-md-5" >
                                    <a href="<?php echo $this->urlLogin; ?>"><img src="http://techulus.com/buttons/fb.png" /></a><br/>
                                    <!--a href="#"><img src="http://techulus.com/buttons/tw.png" /></a><br/>
                                    <a href="#"><img src="http://techulus.com/buttons/gplus.png" /></a-->
                                    <!--br/>
                                    <div class="text-center visible-xs visible-sm">ou</div>
                                    <br/>
                                </div-->
                                <div class="col-md-12">
                                    <form class="form-vertical" method="POST" action="/user/login">
                                            <!--div class="form-group">
                                                <label>
                                                    <input type="radio" name="tipoLogin" value="1" />
                                                    Aluno
                                                </label>
                                                <label>
                                                    <input type="radio" name="tipoLogin" value="2"/>
                                                    Academia
                                                </label>
                                                <label>
                                                    <input type="radio" name="tipoLogin" value="6"/>
                                                    Profissional
                                                </label>
                                                <label>
                                                    <input type="radio" name="tipoLogin" value="4"/>
                                                    Administrador
                                                </label>
                                            </div-->

                                            <div class="form-group">
                                                <input id="textinput" name="identity" type="text" placeholder="Email" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <input id="textinput" name="credential" type="password" placeholder="Senha" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <div class="spacing">
                                                    <input type="checkbox" name="checkboxes" id="checkboxes-0" value="1">
                                                    <small> Remember me</small>
                                                </div>
                                                <div class="spacing">
                                                    <a href="#"><small> Esqueceu sua senha?</small></a>
                                                </div>
                                                <button type="submit" id="singlebutton" name="singlebutton" class="btn btn-primary pull-right">Entrar</button>
                                            </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php }else{
        //USUARIO LOGADO
        //
           if($this->zfcUserIdentity()){ 
                if(!empty($this->zfcUserIdentity()->getIdAluno())){//se for login do aluno
                    $usuario = $this->zfcUserIdentity()->getIdAluno()->getNomeAluno();
                }else if(!empty($this->zfcUserIdentity()->getIdProfissional())){//se for login do profissional
                    $usuario = $this->zfcUserIdentity()->getIdProfissional()->getNome();
                }else if(!empty($this->zfcUserIdentity()->getIdAcademia())){//se for login da academia
                    $usuario = $this->zfcUserIdentity()->getIdAcademia()->getNome();
                }else if(!empty($this->zfcUserIdentity()->getIdAdministrador())){
                    $usuario = "Administrador";
                }
           }?>
            <br/>
            <br/>
            <h1 class="text-center">
                Bem-Vindo <?php echo $usuario; ?>!

            </h1>
            <br/>
            <br/>
   <?php } ?>
   
</div>
