<img width="100%" style="position: relative; top: -10px;" src="<?php echo $this->basePath('img/banner.png'); ?>">
<!--
<div class="jumbotron">
    É dono de uma academia e ainda não possuí um sistema de qualidade? Acompanhe de perto seus alunos e diminua seu esforço de trabalho, com esse sofisticado sistema de acompanhamento de treinos.
    Tenha relatórios de desempenho de seus alunos, dispare avisos para cada um deles, cadastre os treinos e dietas para cada um. Saiba o quanto seu aluno está desenvolvendo através de relatórios e muito mais.
</div>
-->
<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Aplicativo - Play Store') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Faça o download do aplicativo Workout e acompanhe seus treinos, receba dicas de dietas e treinos, pratique atividades físicas e seja acompanhado por esse incrível aplicativo!')); ?></p>
                <p><a class="btn btn-default pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('Download') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Cadastre-se') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('É dono de uma academia? Cadastre-se agora mesmo e acompanhe de perto seus alunos!')); ?></p>
                <p><a class="btn btn-default pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Cadastrar') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Fale Conosco') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Para maiores dúvidas ou esclarecimentos entre em contato através do telefone 0800-01010101')) ?></p>
                <p><a class="btn btn-default pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Fale Conosco') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
