<h1 class="text-center">Consultar Informativo</h1>
<div class="panel panel-default">
  <!-- Default panel contents -->
  

  <!-- Table -->
  <table class="table">
      <thead>
      <tr>
          <th>Descrição</th>
      </tr>
      </thead>
      <tbody
<?php foreach ($this->data as $data): ?>
      <tr> 
        <td><?php echo $data->getDescricao(); ?></td>    
        <td>
            <button type="button" onclick="javascript:window.location.href = '<?php echo $this->url('informativo', ['action' => 'editar', 'id' => $data->getId()]); ?>'"class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </button>
             <button type="button" onclick="confirmarExclusao('<?php echo $this->url('informativo', ['action' => 'excluir', 'id' => $data->getId()]); ?>')" class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </button>
        </td>        
      </tr>
<?php endforeach; ?>
      </tbody>
   </table>
</div>

<div class="paging">
    <?php 
        $paging = $this->paginationHelper($this->data, $this->page, "/informativo/listar/", $this->data->getDefaultItemCountPerPage()); 
        echo $paging; 
    ?>
</div>